#!/usr/bin/env tsx
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, "..", "..");
const DATA = path.join(ROOT, "data");
const OUT = path.join(__dirname, "..", "src", "corpus-data.ts");
const FAQ_PATH = path.join(__dirname, "..", "private", "technical-faq.md");

interface Index {
  meta: { title: string; publishDate: string };
  toc: Array<{ id: string; title: string; level: number; number?: number | null; kind?: string }>;
}

interface Block {
  type: string;
  html?: string;
  text?: string;
}

interface Section {
  id: string;
  title: string;
  level: number;
  blocks?: Block[];
  subsections?: Section[];
}

interface Chapter {
  id: string;
  number?: number | null;
  title: string;
  level: number;
  kind?: string;
  blocks?: Block[];
  subsections?: Section[];
}

function stripHtml(s: string): string {
  return s
    .replace(/<sup[^>]*>.*?<\/sup>/gs, "")     // drop footnote refs
    .replace(/<[^>]+>/g, "")                    // drop remaining tags
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function blockText(b: Block): string {
  if (b.text) return b.text;
  if (b.html) return stripHtml(b.html);
  return "";
}

function renderBlocks(blocks: Block[] | undefined): string {
  if (!blocks) return "";
  return blocks.map(blockText).filter(Boolean).join("\n\n");
}

function renderSubsections(subs: Section[] | undefined, depth = 3): string {
  if (!subs) return "";
  return subs.map(s => {
    const heading = `${"#".repeat(Math.min(depth, 6))} ${s.title}\nanchor: ${s.id}`;
    const body = renderBlocks(s.blocks);
    const nested = renderSubsections(s.subsections, depth + 1);
    return [heading, body, nested].filter(Boolean).join("\n\n");
  }).join("\n\n");
}

function renderChapter(c: Chapter): string {
  const num = c.number ? `Chapter ${c.number} — ` : "";
  const heading = `## ${num}${c.title}\nslug: ${c.id}`;
  const body = renderBlocks(c.blocks);
  const subs = renderSubsections(c.subsections);
  return [heading, body, subs].filter(Boolean).join("\n\n");
}

function main() {
  const index: Index = JSON.parse(fs.readFileSync(path.join(DATA, "index.json"), "utf8"));
  const parts: string[] = [`# ${index.meta.title}\n(${index.meta.publishDate})\n`];
  for (const t of index.toc) {
    const cp = path.join(DATA, "chapters", `${t.id}.json`);
    if (!fs.existsSync(cp)) { console.warn(`skip missing chapter: ${t.id}`); continue; }
    const c: Chapter = JSON.parse(fs.readFileSync(cp, "utf8"));
    parts.push(renderChapter(c));
  }
  const corpus = parts.join("\n\n");
  const faq = fs.readFileSync(FAQ_PATH, "utf8");

  const ts = `// AUTO-GENERATED by scripts/build-corpus.ts. Do not edit by hand.
// Regenerate with: npm run build:corpus
export const REPORT_CORPUS = ${JSON.stringify(corpus)};
export const PRIVATE_FAQ = ${JSON.stringify(faq)};
`;
  fs.writeFileSync(OUT, ts, "utf8");
  const corpusKb = Math.round(corpus.length / 1024);
  const faqKb = Math.round(faq.length / 1024);
  console.log(`Wrote ${OUT} — corpus ${corpusKb}KB, FAQ ${faqKb}KB`);
}

main();
